import { test, expect } from "@playwright/test";

let UNIQUE: string;
let ARTICLE_TITLE: string;
let EDITED_TITLE: string;

test.describe("Blog CRUD", () => {
  test.beforeAll(async () => {
    UNIQUE = `E2E-${Date.now()}`;
    ARTICLE_TITLE = `Test Article ${UNIQUE}`;
    EDITED_TITLE = `${ARTICLE_TITLE} (Revised)`;
  });

  test("list page loads", async ({ page }) => {
    await page.goto("/blog");
    await expect(page.getByRole("heading", { name: /blog/i })).toBeVisible();
    await expect(page.getByRole("link", { name: /new article/i })).toBeVisible();
  });

  test("create a new article", async ({ page }) => {
    await page.goto("/blog/new");
    await page.waitForLoadState("networkidle");

    await page.locator('[name="title"]').fill(ARTICLE_TITLE);
    await page.locator('[name="excerpt"]').fill("A comprehensive E2E test article about real estate trends.");
    await page.locator('[name="content"]').fill(
      "## Introduction\n\nThis is a test article generated by Playwright E2E tests.\n\n## Key Points\n\n- Real estate market insights\n- Investment strategies"
    );
    await page.locator('[name="coverImage"]').fill(
      "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800"
    );
    await page.locator('[name="readTime"]').fill("5");

    await page.getByRole("button", { name: /create article/i }).click();

    await page.waitForURL("**/blog", { timeout: 15_000 });
    await expect(page.getByText(ARTICLE_TITLE)).toBeVisible();
  });

  test("edit an existing article", async ({ page }) => {
    await page.goto("/blog");

    const row = page.locator("tr", { hasText: ARTICLE_TITLE });
    await row.getByRole("link", { name: /edit/i }).click();

    await page.waitForLoadState("networkidle");
    await expect(page.getByRole("heading", { name: /edit article/i })).toBeVisible();

    const titleInput = page.locator('[name="title"]');
    await titleInput.clear();
    await titleInput.fill(EDITED_TITLE);

    await page.getByRole("button", { name: /update article/i }).click();

    await page.waitForURL("**/blog", { timeout: 15_000 });
    await expect(page.getByText(EDITED_TITLE)).toBeVisible();
  });

  test("toggle article published status", async ({ page }) => {
    await page.goto("/blog");

    const row = page.locator("tr", { hasText: EDITED_TITLE });
    const toggleBtn = row.getByRole("button", { name: /publish|unpublish/i });
    const initialLabel = await toggleBtn.getAttribute("aria-label");
    await toggleBtn.click();

    await page.waitForResponse((r) => r.status() === 200);
    await expect(toggleBtn).not.toHaveAttribute("aria-label", initialLabel ?? "");
  });

  test("delete the test article", async ({ page }) => {
    await page.goto("/blog");

    const row = page.locator("tr", { hasText: EDITED_TITLE });
    page.on("dialog", (dialog) => dialog.accept());
    await row.getByRole("button", { name: /delete/i }).click();

    await expect(page.getByText(EDITED_TITLE)).not.toBeVisible({ timeout: 8_000 });
  });
});
